import { CreatePortfolioForm } from "@/components/portfolio/CreatePortfolioForm";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { requireCurrentUser } from "@/lib/current-user";
import prisma from "@/lib/prisma";

export default async function PortfolioPage() {
  const user = await requireCurrentUser();
  const portfolios = await prisma.portfolio.findMany({ where: { userId: user.id }, include: { transactions: { where: { type: { in: ["BUY", "SELL"] } }, orderBy: { occurredAt: "asc" } } }, orderBy: { updatedAt: "desc" } });
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Portfolios</h1><p className="text-sm text-muted-foreground">Track simulated cash and open positions.</p></div><CreatePortfolioForm /></div><div className="grid gap-4 lg:grid-cols-2">{portfolios.map((portfolio) => { const positions = new Map<string, number>(); for (const trade of portfolio.transactions) { if (!trade.symbol || !trade.quantity) continue; positions.set(trade.symbol, (positions.get(trade.symbol) ?? 0) + (trade.type === "BUY" ? trade.quantity : -trade.quantity)); } const open = [...positions].filter(([, quantity]) => quantity > 0.00000001); return <Card key={portfolio.id}><CardHeader><CardTitle>{portfolio.name}</CardTitle><CardDescription>{portfolio.baseCurrency} paper portfolio</CardDescription></CardHeader><CardContent><p className="text-3xl font-semibold">${portfolio.cashBalance.toLocaleString(undefined, { maximumFractionDigits: 2 })}</p><p className="mb-4 text-xs text-muted-foreground">Available cash</p><div className="space-y-2">{open.map(([symbol, quantity]) => <div key={symbol} className="flex justify-between rounded-lg bg-muted/60 p-2 text-sm"><span>{symbol}</span><span className="font-mono">{quantity.toFixed(6)}</span></div>)}{open.length === 0 ? <p className="text-sm text-muted-foreground">No open positions.</p> : null}</div></CardContent></Card>; })}</div>{portfolios.length === 0 ? <div className="grid min-h-56 place-items-center rounded-xl border border-dashed text-muted-foreground">Create your first paper portfolio.</div> : null}</div>;
}
